name: daily_service_log
description: "Daily Service Log Application"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  excel: ^4.0.0
  pdf: ^3.10.8
  printing: ^5.12.0
  path_provider: ^2.1.2
  permission_handler: ^11.3.0
  sqflite: ^2.3.0
  path: ^1.8.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
